### ISSUE TITLE
press & hold motion keys don't repeat (mac)

### ISSUE THREAD

**Issue by josephholsten** [driusan/de#13]
Since we're making due without the nearly-infinite motion keys of vim, I'd like to be able to press-and-hold `j` or `k` to move around.

I'm on a mac. Does press-and-hold work elsewhere, or have I found a feature I get to attempt implementing?

**Comment by josephholsten** [comment]
oh hey, arrow keys. I may decide this is a terrible idea once I spike #14.

**Comment by driusan** [comment]
It works on Linux. I believe it's a bug in the shiny driver, though I haven't looked into it enough to say for sure. (but I thought the same thing about the mousewheel not working and once I looked into the driver to see what was going on realized that it's just the driver acting a little differently between the different OSes)
