### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by jucie** [driusan/de#22]
I downloaded 30 minutes ago. I think something is missing.
Should I "go get" something other than de itself?

> go get github.com/driusan/de
# golang.org/x/exp/shiny/driver/internal/win32
c:\gopath\src\golang.org\x\exp\shiny\driver\internal\win32\zsyscall_windows.go:15: undefined: windows.NewLazySystemDLL
# github.com/driusan/de/renderer
c:\gopath\src\github.com\driusan\de\renderer\defaultsizecalcer.go:32: MonoFontFace.Metrics undefined (type font.Face has no field or method Metrics)
c:\gopath\src\github.com\driusan\de\renderer\defaultsizecalcer.go:47: lineSize.Ceil undefined (type fixed.Int26_6 has no field or method Ceil)
c:\gopath\src\github.com\driusan\de\renderer\defaultsizecalcer.go:48: lineSize.Ceil undefined (type fixed.Int26_6 has no field or method Ceil)
c:\gopath\src\github.com\driusan\de\renderer\imagemap.go:23: r.Min.X.Ceil undefined (type fixed.Int26_6 has no field or method Ceil)
c:\gopath\src\github.com\driusan\de\renderer\imagemap.go:23: r.Max.X.Floor undefined (type fixed.Int26_6 has no field or method Floor)
c:\gopath\src\github.com\driusan\de\renderer\imagemap.go:23: r.Min.Y.Ceil undefined (type fixed.Int26_6 has no field or method Ceil)
c:\gopath\src\github.com\driusan\de\renderer\imagemap.go:23: r.Max.Y.Floor undefined (type fixed.Int26_6 has no field or method Floor)
c:\gopath\src\github.com\driusan\de\renderer\imagemap.go:40: chr.Loc.Min.X.Ceil undefined (type fixed.Int26_6 has no field or method Ceil)
c:\gopath\src\github.com\driusan\de\renderer\imagemap.go:40: chr.Loc.Min.Y.Ceil undefined (type fixed.Int26_6 has no field or method Ceil)
c:\gopath\src\github.com\driusan\de\renderer\imagemap.go:41: chr.Loc.Max.X.Ceil undefined (type fixed.Int26_6 has no field or method Ceil)
c:\gopath\src\github.com\driusan\de\renderer\imagemap.go:41: too many errors

**Comment by driusan** [comment]
It looks like you have old copies of some dependencies that are missing some required methods for de.

Can you run: `go get -u github.com/driusan/de` and see if it works that way? I'll update the README to include the -u flag, since you're not the first person who's had this problem..

**Comment by jucie** [comment]
Yes. The "-u" flag fixed all compilation errors. Thanks, Dave.
