### ISSUE TITLE
(How) Can I open a file's parent directory?

### ISSUE THREAD

**Issue by josephholsten** [driusan/de#25]
I'm generally fine with only having a single buffer open, but I'd like to be able to return to the parent directory in file-listing mode.

I'm fond of netrw/[vinegar](https://github.com/tpope/vim-vinegar)'s `-` keybinding for this, but I think `acme` let me run `..` in the tagbar to do the same.

**Comment by driusan** [comment]
That's odd. `..` or `.` should work. It seems to be working from the buffer, but not from in the tagline.

**Comment by josephholsten** [comment]
that it does! odd.

**Comment by driusan** [comment]
Can you try with the latest build (assuming you're pressing the enter key and not using the mouse)? I just added a fix, hopefully.

**Comment by josephholsten** [comment]
woo! work for me.
