### ISSUE TITLE
Tiny fonts on OS X with HiDPI resolution (aka Retina).

### ISSUE THREAD

**Issue by shurcooL** [driusan/de#8]
This is what I see when I run `de` on its `main.go` file:

![image](https://cloud.githubusercontent.com/assets/1924134/15447365/cb3cfbf6-1ef4-11e6-993b-92175709f1e6.png)

It seems that changing DPI in [`renderer/init.go`](https://github.com/driusan/de/blob/1f89693921bbb40ee5303af6876bce029f7102b6/renderer/init.go#L30) makes it bigger:

![image](https://cloud.githubusercontent.com/assets/1924134/15447378/7d22ad66-1ef5-11e6-8568-9be364e9d127.png)

**Comment by shurcooL** [comment]
For reference, this is what I see on a non-HiDPI resolution on OS X.

![image](https://cloud.githubusercontent.com/assets/1924134/15447487/c24a6548-1ef8-11e6-94d0-06eba405fbd2.png)

**Comment by driusan** [comment]
There's no way that I know of to get the current screen resolution in shiny (or even Go in general.) (In fact, I sent @nigeltao an email yesterday with my thoughts on using shiny and adding a way to get the DPI was one of my suggestions for simple improvements, for this exact reason.)

If someone knows of a way to determine if it's a retina display from the filesystem (ie. if there's a system file that only exists on retina macs, or even one that requires simple parsing to figure out) I can add a hack to set it to 144 if it exists, but I don't have a retina-display Mac to test it on. Otherwise, I think the only solution would be to add a -dpi commandline switch, but that's not very user friendly.

Another thing that I can't test is to see how font hinting affects this on retina displays. Can you try keeping it 72 and changing the hinting to font.HintingFull? I don't think it'll work, but if it does enabling hinting it on darwin builds would be a such simpler fix (the bug that the comment in your screenshot refers to has been fixed downstream, but I've left the font unhinted because I got used to it and because it makes the rendering faster.)

**Comment by shurcooL** [comment]
> Another thing that I can't test is to see how font hinting affects this on retina displays. Can you try keeping it 72 and changing the hinting to font.HintingFull? I don't think it'll work, but if it does enabling hinting it on darwin builds would be a such simpler fix (the bug that the comment in your screenshot refers to has been fixed downstream, but I've left the font unhinted because I got used to it and because it makes the rendering faster.)

I've tried it, but I'm not sure if it's meant to be relevant to the font size issue? [Font hinting](https://en.wikipedia.org/wiki/Font_hinting) is about adjusting its rendering to better fit a pixel grid; it doesn't have an effect on the size of fonts. Perhaps I'm missing something?

The effect of hinting is definitely visible, and it changes the font appearance a lot on non-retina/72 DPI, but much less so on retina/144 DPI.

**Comment by shurcooL** [comment]
> There's no way that I know of to get the current screen resolution in shiny (or even Go in general.) (In fact, I sent @nigeltao an email yesterday with my thoughts on using shiny and adding a way to get the DPI was one of my suggestions for simple improvements, for this exact reason.)

I see. If shiny doesn't support that at the moment, you probably can't do much other than request that support or work on adding it yourself.

This issue is not critical for me, I just reported it because I ran into it.

FWIW, if you were using [glfw](https://github.com/go-gl/glfw), it exposes methods to get the physical framebuffer size as well as the logical window size. With both of those numbers, you can render in a DPI-independent manner (so things appear the same physical size on retina and non-retina displays).

**Comment by driusan** [comment]
> Font hinting is about adjusting its rendering to better fit a pixel grid; it doesn't have an effect on the size of fonts. Perhaps I'm missing something?

No, you're right, that's why I didn't expect it to work. I just wasn't sure if Apple did something funky with hinting on Retina displays to better fit the vertical size (ie. font size) to the retina display grid.

**Comment by shurcooL** [comment]
I can share some screenshots later on, but the overview is that font hinting works as expected on all resolutions.

**Comment by nigeltao** [comment]
"There's no way that I know of to get the current screen resolution in shiny."

It should be available as the PixelsPerPt field in the size.Event event. https://go.googlesource.com/mobile/+/master/event/size/size.go

**Comment by driusan** [comment]
Awesome, thanks!

I never thought to check the size event since I just associated it with window size changes. I looked through the the unit package and the screen package, and did some googling and couldn't find anything.

This should be pretty trivial to fix now..

**Comment by driusan** [comment]
@shurcooL This should be fixed, since I don't have a retina display to check can you confirm for me?

**Comment by nigeltao** [comment]
Just a style nit:

dpi == float32(0)
and
Size:    float64(16),
and
RecalculateFontFace(72.0)

can be

dpi == 0
and
Size:    16,
and
RecalculateFontFace(72)

as per https://blog.golang.org/constants

**Comment by shurcooL** [comment]
> @shurcooL This should be fixed, since I don't have a retina display to check can you confirm for me?

It is not fixed by commit b12912bec18f39f090fa46cfb761d494e430aba3, it has multiple issues in it. I'll post comments inline.

**Comment by driusan** [comment]
@shurcooL There were a couple stupid bugs in b12912b that should be fixed by 4123941. I still don't have a Mac where I can test it handy, but it seems to work more accurately on X11 (I just didn't notice in b12912b because, as you pointed out, I forgot to actually use the variable.)

**Comment by shurcooL** [comment]
I can confirm that 4123941a67247bb243cac341c9fc859b4468ab60 fixes the issue where the font size was different between normal and HiDPI resolutions. Fonts appear the same size on display in both modes now.

1152x720 physical resolution, 1152x720 logical resolution (normal, non-HiDPI mode):

![screen shot 2016-05-22 at 10 37 42 am](https://cloud.githubusercontent.com/assets/1924134/15455545/4989de8a-200c-11e6-80ea-37d6158a0cd6.png)

2304x1440 physical resolution, 1152x720 logical resolution (2x HiDPI mode):

<img width="1152" alt="screen shot 2016-05-22 at 10 39 39 am" src="https://cloud.githubusercontent.com/assets/1924134/15455547/5be4aa9c-200c-11e6-836b-7d7615189979.png">

However, the actual font size seems a little too high. If I uncomment the `fmt.Printf` at top of `RecalculateFontFace`, I see the following output on 1680x1050 resolution on a 15.4" screen:

```
DPI: 72.000000
DPI: 128.999997
```

On a slightly lower resolution of 1440x900 on the same 15.4" screen, the second value is different:

```
DPI: 72.000000
DPI: 110.999997
```

(The first value is the default hardcoded 72 in code, the second is dynamically set from `size.Event`.)

So it seems on OS X it takes the display size and resolution into account when reporting `PixelsPerPt`.

Perhaps Linux doesn't do that and that's why you're not able to see this in your local testing?

I think if I were to use `de` myself right now, I'd just modify the code to have the font be of size that suits my needs. So I don't think you need to worry about it too much, and it's probably easier for you to resolve this at a later time once other features are done, and you have access to a OS X machine and decide to prioritize its support.

I'll close this because I don't want to create extra work for you. But if you want to, feel free to reopen and keep working on this.

**Comment by shurcooL** [comment]
Also, since I haven't already mentioned this, `de` looks like a really cool project and I will eagerly follow its development. I think the idea is fantastic - I am, in theory at least, a fan of both ACME and vim/emacs but not the fact they're not as easy as running `go get` to run on my computer. `de` solves that problem, and I think it's looking really great so far! :)

**Comment by driusan** [comment]
@shurcooL I realized my work laptop has a retina display, so I brought it home to check it out and I see what you mean.

Technically, there's 72 points in an inch. It's the definition of a point, so OS X is reporting it correctly. Since it's a 12pt font and the DPI was calculating taking that into account, it's rendering at the same physical size on the screen independently of screen resolution.

The problem is that when you change the resolution on your laptop, you don't expect font sizes to scale up and take that into account, but I'm not sure what the solution is.
